name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ACR_NAME: rbtacr
  RESOURCE_GROUP: Robert-Lordache-Candidate
  CLUSTER_NAME: rbt-aks-cluster
  AZURE_SUBSCRIPTION: b99c0710-ded3-407b-b632-9fb5dd7edd13

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set Azure subscription
      run: |
        az account set --subscription ${{ env.AZURE_SUBSCRIPTION }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.ACR_NAME }}.azurecr.io/2bcloud-app:latest
          ${{ env.ACR_NAME }}.azurecr.io/2bcloud-app:${{ github.sha }}

    - name: Get Kube Config
      run: |
        az aks get-credentials --resource-group ${{ env.RESOURCE_GROUP }} --name ${{ env.CLUSTER_NAME }} --file $GITHUB_WORKSPACE/kubeconfig
        echo "KUBE_CONFIG=$(cat $GITHUB_WORKSPACE/kubeconfig | base64 -w 0)" >> $GITHUB_ENV

    - name: Set up kubectl
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ env.KUBE_CONFIG }}

    - name: Deploy to Kubernetes
      run: |
        # Replace placeholders in deployment.yaml
        sed -i "s|\${{ secrets.ACR_NAME }}.azurecr.io/2bcloud-app:latest|${{ env.ACR_NAME }}.azurecr.io/2bcloud-app:${{ github.sha }}|g" kubernetes/deployment.yaml
        
        # Apply Kubernetes manifests
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/hpa.yaml
        
        # Check deployment status
        kubectl rollout status deployment/2bcloud-app
        
        # Get service URL
        kubectl get service 2bcloud-app-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      
    - name: Verify deployment
      run: |
        # Wait for pods to be ready
        kubectl wait --for=condition=ready pod -l app=2bcloud-app --timeout=300s
        
        # Get service URL
        SERVICE_IP=$(kubectl get service 2bcloud-app-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "Application deployed at: http://$SERVICE_IP"
        
        # Run smoke test
        curl -sSf http://$SERVICE_IP/healthz
