name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.ACR_NAME }}.azurecr.io/2bcloud-app:latest
          ${{ env.ACR_NAME }}.azurecr.io/2bcloud-app:${{ github.sha }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Get Kubernetes context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.CLUSTER_NAME }}
        admin: true

    - name: Deploy to Kubernetes
      run: |
        # Replace placeholders in deployment.yaml
        sed -i "s|\${{ secrets.ACR_NAME }}.azurecr.io/2bcloud-app:latest|${{ env.ACR_NAME }}.azurecr.io/2bcloud-app:${{ github.sha }}|g" kubernetes/deployment.yaml
        
        # Apply Kubernetes manifests
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/hpa.yaml
        
        # Check deployment status
        kubectl rollout status deployment/2bcloud-app
        
        # Get service URL
        kubectl get service 2bcloud-app-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      
    - name: Verify deployment
      run: |
        # Wait for pods to be ready
        kubectl wait --for=condition=ready pod -l app=2bcloud-app --timeout=300s
        
        # Get service URL
        SERVICE_IP=$(kubectl get service 2bcloud-app-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "Application deployed at: http://$SERVICE_IP"
        
        # Run smoke test
        curl -sSf http://$SERVICE_IP/healthz
